all: True
recursive: True
disable-version-string: True
mockname: "{{.InterfaceName}}"
filename: "mock_{{.InterfaceName}}.go"
with-expecter: False
outpkg: "mocks"
packages:

  CaliYa/cmd/api/handler:
    config:
    dir: "mocks/cmd/api/handler"
