// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	"CaliYa/core/domain/models/orders"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// OrdersApp is an autogenerated mock type for the OrdersApp type
type OrdersApp struct {
	mock.Mock
}

// RegisterOrders provides a mock function with given fields: ctx, order
func (_m *OrdersApp) RegisterOrders(ctx context.Context, order orders.Order) error {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for RegisterOrders")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, orders.Order) error); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewOrdersApp creates a new instance of OrdersApp. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrdersApp(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrdersApp {
	mock := &OrdersApp{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
