// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	models "CaliYa/core/domain/models"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// OrdersRepo is an autogenerated mock type for the OrdersRepo type
type OrdersRepo struct {
	mock.Mock
}

// CalculatePrice provides a mock function with given fields: ctx, order
func (_m *OrdersRepo) CalculatePrice(ctx context.Context, order *models.Order) {
	_m.Called(ctx, order)
}

// RegisterOrders provides a mock function with given fields: ctx, order
func (_m *OrdersRepo) RegisterOrders(ctx context.Context, order *models.Order) error {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for RegisterOrders")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Order) error); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewOrdersRepo creates a new instance of OrdersRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrdersRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrdersRepo {
	mock := &OrdersRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
