// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	models "CaliYa/core/domain/models"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// PromotionsRepository is an autogenerated mock type for the PromotionsRepository type
type PromotionsRepository struct {
	mock.Mock
}

// GetPromotions provides a mock function with given fields: ctx
func (_m *PromotionsRepository) GetPromotions(ctx context.Context) ([]models.ItemsPromo, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetPromotions")
	}

	var r0 []models.ItemsPromo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.ItemsPromo, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.ItemsPromo); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.ItemsPromo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPromotionsRepository creates a new instance of PromotionsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPromotionsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PromotionsRepository {
	mock := &PromotionsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
