name: Clone Repository on Merge

on:
  push:
    branches:
      - develop

jobs:
  clone:
    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.KEY_PRE_PROD }}

    - name: Clone repository on remote server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.USER_PRE_PROD }}@${{ secrets.HOST_PRE_PROD }} << 'EOF'
          set -e

          # Ruta donde quieres clonar el repo
          cd develop/encargalo/Encargalo.app-api

          # Clonar el repositorio (si ya existe, puedes borrar o hacer pull)
          if [ ! -d "Encargalo.app-api" ]; then
            git clone https://github.com/tu_usuario/tu_repo.git Encargalo.app-api
          else
            cd Encargalo.app-api
            git fetch origin
            git reset --hard origin/develop
          fi
        EOF
